# Generated by Django 5.2 on 2025-12-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_usuario')),
                ('nombre', models.CharField(verbose_name='nombre_usuario')),
                ('email', models.CharField(verbose_name='email_usuario')),
                ('contraseña_hash', models.CharField(verbose_name='contraseña_usuario')),
                ('rol', models.CharField(verbose_name='rol_usuario')),
                ('fecha_creacion', models.DateField(verbose_name='fecha_usuario')),
            ],
        ),
    ]
